#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVER_PATH="$SCRIPT_DIR/mcp-server/server.js"

echo ""
echo "CloseLoop setup"
echo "================"
echo ""

# Install deps
echo "Installing server dependencies..."
cd "$SCRIPT_DIR/mcp-server" && npm install --silent
echo "Done."
echo ""

echo "┌─────────────────────────────────────────────────────────┐"
echo "│  Two steps to get started:                              │"
echo "└─────────────────────────────────────────────────────────┘"
echo ""
echo "1. Load the Chrome extension"
echo "   → Open Chrome → chrome://extensions"
echo "   → Enable Developer mode (top right toggle)"
echo "   → Click 'Load unpacked'"
echo "   → Select: $SCRIPT_DIR/extension"
echo ""
echo "2. Start the local server"
echo "   → node $SERVER_PATH"
echo ""
echo "That's it. The extension popup turns green when connected."
echo "Click 'Copy instructions for your AI' and paste into Claude Code."
echo ""
echo "────────────────────────────────────────────────────────────"
echo "Demo: open the broken calculator in Chrome to try it:"
echo "  file://$SCRIPT_DIR/demo/calculator/index.html"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Server endpoints (Claude Code calls these via curl Bash tool):"
echo "  GET  http://localhost:9009/context"
echo "  POST http://localhost:9009/screenshot   → saves to /tmp/closedloop-screenshot.png"
echo "  POST http://localhost:9009/click        body: {\"selector\":\"...\"}"
echo "  POST http://localhost:9009/type         body: {\"selector\":\"...\",\"text\":\"...\"}"
echo "  POST http://localhost:9009/navigate     body: {\"url\":\"...\"}"
echo "  POST http://localhost:9009/attach-debugger"
echo "  GET  http://localhost:9009/console-errors"
echo "  GET  http://localhost:9009/network-errors"
echo ""
